server:
  port: 8083
  servlet:
    context-path: /pairSerial
    
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        generate_statistics: true
        jdbc:
          batch_size: 1000
          order_inserts: true
          order_updates: true
  regional-data-source:
    jndiName: java:jboss/RegionalDS

